# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secret
#   namespace: my-pro
# type: Opaque
# data:
#   MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= 
#   MYSQL_DATABASE: YmFua2FwcGRi

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: myapp-config
#   namespace: my-pro
# data:
#   MYSQL_DATABASE: "bankappdb"

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: ebs-sc
#   namespace: my-pro
# provisioner: ebs.csi.aws.com
# parameters:
#   type: gp3
#   fsType: ext4
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: myapp-pvc
#   namespace: my-pro
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: ebs-sc

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: myapp-mysqldeployment
#   namespace: my-pro
# spec:
#   selector:
#     matchLabels:
#       app: mysql
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - name: mysql
#           image: mysql:8.0
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secret
#                   key: MYSQL_ROOT_PASSWORD
#             - name: MYSQL_DATABASE
#               valueFrom:
#                 configMapKeyRef:
#                   name: myapp-config
#                   key: MYSQL_DATABASE
#           ports:
#             - containerPort: 3306
#           volumeMounts: 
#             - name: mysql-persistent-storage
#               mountPath: /var/lib/mysql
#           resources:
#             requests:
#               memory: "512Mi"
#               cpu: "500m"
#             limits:
#               memory: "1Gi"
#               cpu: "1"
#       volumes: 
#         - name: mysql-persistent-storage
#           persistentVolumeClaim:
#             claimName: myapp-pvc

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-mysqlservice
#   namespace: my-pro
# spec:
#   selector:
#     app: mysql
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#   type: ClusterIP

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: bankapp
#   namespace: my-pro
# spec:
#   selector:
#     matchLabels:
#       app: bankapp
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app: bankapp
#     spec:
#       containers:
#         - name: bankapp
#           image: adijaiswal/bankapp:latest
#           env:
#             - name: SPRING_DATA_MYSQL_URL
#               value: jdbc:mysql://myapp-mysqlservice:3306/bankappdb?USEssl=false&timezone=UTC&allowPublicKeyRetrieval=true
#             - name: MYSQL_ROOT_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secret
#                   key: MYSQL_ROOT_PASSWORD
#             - name: MYSQL_DATABASE
#               valueFrom:
#                 configMapKeyRef:
#                   name: myapp-config
#                   key: MYSQL_DATABASE
#           ports:
#             - containerPort: 8080
#           resources:
#             requests:
#               memory: "512Mi"
#               cpu: "500m"
#             limits:
#               memory: "1Gi"
#               cpu: "1"  
#             livenessProbe:
#                 httpGet:  
#                 path: /health
#                 port: 8080
#                 initialDelaySeconds: 30
#                 periodSeconds: 10
#                 timeoutSeconds: 10

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: bankapp-service
#   namespace: my-pro
# spec:
#   selector:
#     app: bankapp
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer





-------------------------------------------

---

apiVersion: v1
kind: secret
metadata:
  name: mysql-secret
  namespace: my-pro





























